CREATE ROLE app_user WITH
  LOGIN
  PASSWORD 'app_password'
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOBYPASSRLS;

GRANT CONNECT ON DATABASE postgres TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE organization TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE customer TO app_user;
